#!/usr/bin/env python3.7

import click

__version__ = "0.1"

@click.command()
@click.option("--version", "-v", count=True)
def main(version):
    if version:
        print("personal_bin v{:s}".format(__version__))

if __name__ == "__main__":
    main()
